---
dotfiles_install_packages: true
dotfiles_install_vscode: true
dotfiles_install_vscode_extensions: true
dotfiles_install_termusic: true
dotfiles_install_nvim_deps: true
dotfiles_install_claude: true
dotfiles_set_default_shell: false
