#!/bin/bash

# JankyBorders configuration - Tokyo Night Storm theme
# Docs: https://github.com/FelixKratz/JankyBorders

options=(
  style=round
  width=5.0
  hidpi=on
  active_color=0xff7aa2f7   # Blue - Tokyo Night
  inactive_color=0xff414868 # Grey - Tokyo Night
)

borders "${options[@]}"
