-- ╭─────────────────────────────────────────────────────────────╮
-- │ Python Filetype Settings                                    │
-- ╰─────────────────────────────────────────────────────────────╯
--
-- This file provides Python-specific settings for notebook-style
-- development using cell markers (# %%) with molten-nvim.
--
-- KEYBINDINGS (from python.lua):
-- ──────────────────────────────────────────────────────────────
-- Jupyter/Molten (<leader>j):
--   <leader>ji    Initialize kernel (select)
--   <leader>jI    Initialize kernel (auto from venv)
--   <leader>jc    Run current cell
--   <leader>jl    Evaluate line
--   <leader>je    Evaluate operator (motion)
--   <leader>jr    Re-evaluate cell
--   <leader>jv    Evaluate visual selection (visual mode)
--   <leader>jo    Show output
--   <leader>jO    Enter output window (interact with it)
--   <leader>jh    Hide output
--   <leader>jd    Delete cell output
--   <leader>jD    Delete all outputs
--   <leader>jx    Interrupt kernel
--   <leader>js    Save outputs
--   <leader>jL    Load outputs
--   <leader>jE    Export to .ipynb
--   <leader>jM    Import from .ipynb
--   <leader>j]    Next cell
--   <leader>j[    Previous cell
--
-- Cell Navigation:
--   ]x / [x       Next/previous cell (# %% markers)
--
-- Cell Text Objects (vim-textobj-hydrogen):
--   ih            Inner cell (content between markers)
--   ah            Around cell (including marker)
--   dih / yih     Delete/yank inner cell
--   cih           Change inner cell
--   vih           Select inner cell
--
-- REPL (<leader>r) - iron.nvim with IPython:
--   <leader>rs    Start REPL
--   <leader>rr    Restart REPL
--   <leader>rf    Focus REPL
--   <leader>rh    Hide REPL
--   <leader>rc    Send motion/visual to REPL
--   <leader>rl    Send line
--   <leader>rp    Send paragraph
--   <leader>rF    Send file
--   <leader>ru    Send until cursor
--   <leader>ri    Interrupt
--   <leader>rq    Quit REPL
--   <leader>rx    Clear REPL
--
-- Testing (<leader>t) - neotest with pytest:
--   <leader>tp    Run nearest test
--   <leader>tP    Run file tests
--   <leader>td    Debug nearest test
--
-- Virtual Environment (<leader>c):
--   <leader>cv    Select venv
--   <leader>cV    Select cached venv
--
-- ──────────────────────────────────────────────────────────────

-- Optional: Folding based on cell markers (uncomment if desired)
-- vim.opt_local.foldmethod = "expr"
-- vim.opt_local.foldexpr = "getline(v:lnum)=~'^# %%'?'>1':'='"

-- Optional: Enable conceal for cleaner display
-- vim.opt_local.conceallevel = 2
