---
- name: Provision dotfiles
  hosts: "{{ dotfiles_target | default('local') }}"
  gather_facts: true

  vars:
    dotfiles_controller_dir: "{{ playbook_dir | dirname }}"

  roles:
    - role: dotfiles
